#!/bin/sh
set -eu

envsubst '${VITE_API_BASE_URL} ${VITE_NUDGEE_ANDROID_URL} ${VITE_NUDGEE_IOS_URL} ${VITE_NUDGER_REGISTER_URL} ${VITE_NUDGER_LOGIN_URL} ${VITE_PROFILE_IMAGE_SOURCE_MAX_BYTES} ${VITE_PROFILE_IMAGE_FINAL_MAX_BYTES} ${VITE_PROFILE_IMAGE_MAX_DIMENSION} ${VITE_PROFILE_IMAGE_WEBP_QUALITY} ${VITE_PROFILE_IMAGE_PRESIGN_URL_TTL_SECONDS}' \
  < /usr/share/nginx/html/runtime-config.template.js \
  > /usr/share/nginx/html/runtime-config.js

exec "$@"
